apiVersion: apps/v1
kind: Deployment
metadata:
  name: senre-service
  namespace: service-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: senre-service
  template:
    metadata:
      labels:
        app: senre-service
    spec:
      containers:
        - name: senre-service
          image: senre/crayon-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi